#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
  remove|upgrade)
    if command -v systemctl >/dev/null 2>&1; then
      systemctl stop conveyor.service >/dev/null 2>&1 || true
      systemctl disable conveyor.service >/dev/null 2>&1 || true
    fi
  ;;
esac

exit 0