# Edit this file to configure your Docker Compose setup
services:
  app:
    image: ghcr.io/open-ug/conveyor:latest
    container_name: app
    ports:
      - "8080:8080"
      - "4222:4222"
    networks:
      - conveyor-network

volumes:
  app-data:

networks:
  conveyor-network:
    driver: bridge
